
exp_id: test

# checkpoint
checkpoint_type: pretrained
checkpoint_path: ./checkpoints/pretrain-mae-base-80.pth

# data
seed: 42
device: cuda
batch_size: 4
num_workers: 4
num_classes: 100
warmup_iter: 4000

# optim
lr: 0.0001
optim_mode: decay
scheduler_gamma: 0.1
scheduler_step_size: 10

# training
num_epochs: 20
export_bound: 10
train_print_freq: 500

# FPN
embed_dim: 768
out_dim: 256
extra_pool: 2

# detection
anchor_sizes: [16, 32, 64, 128, 256, 512]
anchor_aspect_ratios: [0.5, 1.0, 2.0]
roi_align_output_size: 4
roi_align_feats: ["0", "1", "2", "3", "pool1", "pool2"]
roi_align_sampling_ratio: 2